/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_CallEventRecordType_H_
#define	_CallEventRecordType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CallEventRecordType {
	CallEventRecordType_moCallRecord	= 0,
	CallEventRecordType_mtCallRecord	= 1,
	CallEventRecordType_roamingRecord	= 2,
	CallEventRecordType_incGatewayRecord	= 3,
	CallEventRecordType_outGatewayRecord	= 4,
	CallEventRecordType_transitCallRecord	= 5,
	CallEventRecordType_moSMSRecord	= 6,
	CallEventRecordType_mtSMSRecord	= 7,
	CallEventRecordType_moSMSIWRecord	= 8,
	CallEventRecordType_mtSMSGWRecord	= 9,
	CallEventRecordType_ssActionRecord	= 10,
	CallEventRecordType_hlrIntRecord	= 11,
	CallEventRecordType_locUpdateHLRRecord	= 12,
	CallEventRecordType_locUpdateVLRRecord	= 13,
	CallEventRecordType_commonEquipRecord	= 14,
	CallEventRecordType_moTraceRecord	= 15,
	CallEventRecordType_mtTraceRecord	= 16,
	CallEventRecordType_termCAMELRecord	= 17,
	CallEventRecordType_sgsnPDPRecord	= 18,
	CallEventRecordType_ggsnPDPRecord	= 19,
	CallEventRecordType_sgsnMMRecord	= 20,
	CallEventRecordType_sgsnSMORecord	= 21,
	CallEventRecordType_sgsnSMTRecord	= 22,
	CallEventRecordType_mtLCSRecord	= 23,
	CallEventRecordType_moLCSRecord	= 24,
	CallEventRecordType_niLCSRecord	= 25,
	CallEventRecordType_sgsnMtLCSRecord	= 26,
	CallEventRecordType_sgsnMoLCSRecord	= 27,
	CallEventRecordType_sgsnNiLCSRecord	= 28,
	CallEventRecordType_mmO1SRecord	= 29,
	CallEventRecordType_mmO4FRqRecord	= 30,
	CallEventRecordType_mmO4FRsRecord	= 31,
	CallEventRecordType_mmO4DRecord	= 32,
	CallEventRecordType_mmO1DRecord	= 33,
	CallEventRecordType_mmO4RRecord	= 34,
	CallEventRecordType_mmO1RRecord	= 35,
	CallEventRecordType_mmOMDRecord	= 36,
	CallEventRecordType_mmR4FRecord	= 37,
	CallEventRecordType_mmR1NRqRecord	= 38,
	CallEventRecordType_mmR1NRsRecord	= 39,
	CallEventRecordType_mmR1RtRecord	= 40,
	CallEventRecordType_mmR1AFRecord	= 42,
	CallEventRecordType_mmR4DRqRecord	= 43,
	CallEventRecordType_mmR4DRsRecord	= 44,
	CallEventRecordType_mmR1RRRecord	= 45,
	CallEventRecordType_mmR4RRqRecord	= 46,
	CallEventRecordType_mmR4RRsRecord	= 47,
	CallEventRecordType_mmRMDRecord	= 48,
	CallEventRecordType_mmFRecord	= 49,
	CallEventRecordType_mmBx1SRecord	= 50,
	CallEventRecordType_mmBx1VRecord	= 51,
	CallEventRecordType_mmBx1URecord	= 52,
	CallEventRecordType_mmBx1DRecord	= 53,
	CallEventRecordType_mM7SRecord	= 54,
	CallEventRecordType_mM7DRqRecord	= 55,
	CallEventRecordType_mM7DRsRecord	= 56,
	CallEventRecordType_mM7CRecord	= 57,
	CallEventRecordType_mM7RRecord	= 58,
	CallEventRecordType_mM7DRRqRecord	= 59,
	CallEventRecordType_mM7DRRsRecord	= 60,
	CallEventRecordType_mM7RRqRecord	= 61,
	CallEventRecordType_mM7RRsRecord	= 62,
	CallEventRecordType_s_CSCFRecord	= 63,
	CallEventRecordType_p_CSCFRecord	= 64,
	CallEventRecordType_i_CSCFRecord	= 65,
	CallEventRecordType_mRFCRecord	= 66,
	CallEventRecordType_mGCFRecord	= 67,
	CallEventRecordType_bGCFRecord	= 68,
	CallEventRecordType_aSRecord	= 69,
	CallEventRecordType_egsnPDPRecord	= 70,
	CallEventRecordType_lCSGMORecord	= 71,
	CallEventRecordType_lCSRGMTRecord	= 72,
	CallEventRecordType_lCSHGMTRecord	= 73,
	CallEventRecordType_lCSVGMTRecord	= 74,
	CallEventRecordType_lCSGNIRecord	= 75,
	CallEventRecordType_sgsnMBMSRecord	= 76,
	CallEventRecordType_ggsnMBMSRecord	= 77,
	CallEventRecordType_subBMSCRecord	= 78,
	CallEventRecordType_contentBMSCRecord	= 79,
	CallEventRecordType_pPFRecord	= 80,
	CallEventRecordType_cPFRecord	= 81
} e_CallEventRecordType;

/* CallEventRecordType */
typedef long	 CallEventRecordType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CallEventRecordType;
asn_struct_free_f CallEventRecordType_free;
asn_struct_print_f CallEventRecordType_print;
asn_constr_check_f CallEventRecordType_constraint;
ber_type_decoder_f CallEventRecordType_decode_ber;
der_type_encoder_f CallEventRecordType_encode_der;
xer_type_decoder_f CallEventRecordType_decode_xer;
xer_type_encoder_f CallEventRecordType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CallEventRecordType_H_ */
#include <asn_internal.h>
