/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_CNIPMulticastDistribution_H_
#define	_CNIPMulticastDistribution_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CNIPMulticastDistribution {
	CNIPMulticastDistribution_nO_IP_MULTICAST	= 0,
	CNIPMulticastDistribution_iP_MULTICAST	= 1
} e_CNIPMulticastDistribution;

/* CNIPMulticastDistribution */
typedef long	 CNIPMulticastDistribution_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CNIPMulticastDistribution;
asn_struct_free_f CNIPMulticastDistribution_free;
asn_struct_print_f CNIPMulticastDistribution_print;
asn_constr_check_f CNIPMulticastDistribution_constraint;
ber_type_decoder_f CNIPMulticastDistribution_decode_ber;
der_type_encoder_f CNIPMulticastDistribution_encode_der;
xer_type_decoder_f CNIPMulticastDistribution_decode_xer;
xer_type_encoder_f CNIPMulticastDistribution_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _CNIPMulticastDistribution_H_ */
#include <asn_internal.h>
