/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_Ext_BearerServiceCode_H_
#define	_Ext_BearerServiceCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Ext-BearerServiceCode */
typedef OCTET_STRING_t	 Ext_BearerServiceCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ext_BearerServiceCode;
asn_struct_free_f Ext_BearerServiceCode_free;
asn_struct_print_f Ext_BearerServiceCode_print;
asn_constr_check_f Ext_BearerServiceCode_constraint;
ber_type_decoder_f Ext_BearerServiceCode_decode_ber;
der_type_encoder_f Ext_BearerServiceCode_encode_der;
xer_type_decoder_f Ext_BearerServiceCode_decode_xer;
xer_type_encoder_f Ext_BearerServiceCode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Ext_BearerServiceCode_H_ */
#include <asn_internal.h>
