/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_GPRSRecord_H_
#define	_GPRSRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SGSNPDPRecord.h"
#include "SGSNMMRecord.h"
#include "SGSNSMORecord.h"
#include "SGSNSMTRecord.h"
#include "SGWRecord.h"
#include "PGWRecord.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum GPRSRecord_PR {
	GPRSRecord_PR_NOTHING,	/* No components present */
	GPRSRecord_PR_sgsnPDPRecord,
	GPRSRecord_PR_sgsnMMRecord,
	GPRSRecord_PR_sgsnSMORecord,
	GPRSRecord_PR_sgsnSMTRecord,
	GPRSRecord_PR_sGWRecord,
	GPRSRecord_PR_pGWRecord
} GPRSRecord_PR;

/* GPRSRecord */
typedef struct GPRSRecord {
	GPRSRecord_PR present;
	union GPRSRecord_u {
		SGSNPDPRecord_t	 sgsnPDPRecord;
		SGSNMMRecord_t	 sgsnMMRecord;
		SGSNSMORecord_t	 sgsnSMORecord;
		SGSNSMTRecord_t	 sgsnSMTRecord;
		SGWRecord_t	 sGWRecord;
		PGWRecord_t	 pGWRecord;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GPRSRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GPRSRecord;

#ifdef __cplusplus
}
#endif

#endif	/* _GPRSRecord_H_ */
#include <asn_internal.h>
