/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_LCSClientIdentity_H_
#define	_LCSClientIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AddressString.h"
#include "LCSClientInternalID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LCSClientExternalID;

/* LCSClientIdentity */
typedef struct LCSClientIdentity {
	struct LCSClientExternalID	*lcsClientExternalID	/* OPTIONAL */;
	AddressString_t	*lcsClientDialedByMS	/* OPTIONAL */;
	LCSClientInternalID_t	*lcsClientInternalID	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LCSClientIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LCSClientIdentity;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LCSClientExternalID.h"

#endif	/* _LCSClientIdentity_H_ */
#include <asn_internal.h>
