/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_MBMSInformation_H_
#define	_MBMSInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TMGI.h"
#include "MBMSSessionIdentity.h"
#include "MBMSServiceType.h"
#include "MBMSUserServiceType.h"
#include "MBMS2G3GIndicator.h"
#include <BOOLEAN.h>
#include "RoutingAreaCode.h"
#include "MBMSServiceArea.h"
#include "RequiredMBMSBearerCapabilities.h"
#include "CNIPMulticastDistribution.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum MBMSInformation_PR {
	MBMSInformation_PR_tMGI,	/* Member tMGI is present */
	MBMSInformation_PR_mBMSSessionIdentity,	/* Member mBMSSessionIdentity is present */
	MBMSInformation_PR_mBMSServiceType,	/* Member mBMSServiceType is present */
	MBMSInformation_PR_mBMSUserServiceType,	/* Member mBMSUserServiceType is present */
	MBMSInformation_PR_mBMS2G3GIndicator,	/* Member mBMS2G3GIndicator is present */
	MBMSInformation_PR_fileRepairSupported,	/* Member fileRepairSupported is present */
	MBMSInformation_PR_rAI,	/* Member rAI is present */
	MBMSInformation_PR_mBMSServiceArea,	/* Member mBMSServiceArea is present */
	MBMSInformation_PR_requiredMBMSBearerCaps,	/* Member requiredMBMSBearerCaps is present */
	MBMSInformation_PR_mBMSGWAddress,	/* Member mBMSGWAddress is present */
	MBMSInformation_PR_cNIPMulticastDistribution,	/* Member cNIPMulticastDistribution is present */
} MBMSInformation_PR;

/* Forward declarations */
struct IPAddress;

/* MBMSInformation */
typedef struct MBMSInformation {
	TMGI_t	*tMGI	/* OPTIONAL */;
	MBMSSessionIdentity_t	*mBMSSessionIdentity	/* OPTIONAL */;
	MBMSServiceType_t	*mBMSServiceType	/* OPTIONAL */;
	MBMSUserServiceType_t	*mBMSUserServiceType	/* OPTIONAL */;
	MBMS2G3GIndicator_t	*mBMS2G3GIndicator	/* OPTIONAL */;
	BOOLEAN_t	*fileRepairSupported	/* OPTIONAL */;
	RoutingAreaCode_t	*rAI	/* OPTIONAL */;
	MBMSServiceArea_t	*mBMSServiceArea	/* OPTIONAL */;
	RequiredMBMSBearerCapabilities_t	*requiredMBMSBearerCaps	/* OPTIONAL */;
	struct IPAddress	*mBMSGWAddress	/* OPTIONAL */;
	CNIPMulticastDistribution_t	*cNIPMulticastDistribution	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pMBMSInformation, MBMSInformation_PR_x) */
	unsigned int _presence_map
		[((11+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBMSInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMSInformation;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "GSNAddress.h"

#endif	/* _MBMSInformation_H_ */
#include <asn_internal.h>
