/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_MBMSServiceType_H_
#define	_MBMSServiceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBMSServiceType {
	MBMSServiceType_mULTICAST	= 0,
	MBMSServiceType_bROADCAST	= 1
} e_MBMSServiceType;

/* MBMSServiceType */
typedef long	 MBMSServiceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMSServiceType;
asn_struct_free_f MBMSServiceType_free;
asn_struct_print_f MBMSServiceType_print;
asn_constr_check_f MBMSServiceType_constraint;
ber_type_decoder_f MBMSServiceType_decode_ber;
der_type_encoder_f MBMSServiceType_encode_der;
xer_type_decoder_f MBMSServiceType_decode_xer;
xer_type_encoder_f MBMSServiceType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMSServiceType_H_ */
#include <asn_internal.h>
