/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#include "MBMSInformation.h"

static asn_TYPE_member_t asn_MBR_MBMSInformation_1[] = {
	{ ATF_POINTER, 11, offsetof(struct MBMSInformation, tMGI),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TMGI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tMGI"
		},
	{ ATF_POINTER, 10, offsetof(struct MBMSInformation, mBMSSessionIdentity),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSSessionIdentity,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mBMSSessionIdentity"
		},
	{ ATF_POINTER, 9, offsetof(struct MBMSInformation, mBMSServiceType),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSServiceType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mBMSServiceType"
		},
	{ ATF_POINTER, 8, offsetof(struct MBMSInformation, mBMSUserServiceType),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSUserServiceType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mBMSUserServiceType"
		},
	{ ATF_POINTER, 7, offsetof(struct MBMSInformation, mBMS2G3GIndicator),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMS2G3GIndicator,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mBMS2G3GIndicator"
		},
	{ ATF_POINTER, 6, offsetof(struct MBMSInformation, fileRepairSupported),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fileRepairSupported"
		},
	{ ATF_POINTER, 5, offsetof(struct MBMSInformation, rAI),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoutingAreaCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rAI"
		},
	{ ATF_POINTER, 4, offsetof(struct MBMSInformation, mBMSServiceArea),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MBMSServiceArea,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mBMSServiceArea"
		},
	{ ATF_POINTER, 3, offsetof(struct MBMSInformation, requiredMBMSBearerCaps),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RequiredMBMSBearerCapabilities,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"requiredMBMSBearerCaps"
		},
	{ ATF_POINTER, 2, offsetof(struct MBMSInformation, mBMSGWAddress),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GSNAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"mBMSGWAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct MBMSInformation, cNIPMulticastDistribution),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CNIPMulticastDistribution,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cNIPMulticastDistribution"
		},
};
static ber_tlv_tag_t asn_DEF_MBMSInformation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_MBMSInformation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* tMGI */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* mBMSSessionIdentity */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* mBMSServiceType */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* mBMSUserServiceType */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* mBMS2G3GIndicator */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* fileRepairSupported */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* rAI */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* mBMSServiceArea */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 }, /* requiredMBMSBearerCaps */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 9, 0, 0 }, /* mBMSGWAddress */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 10, 0, 0 } /* cNIPMulticastDistribution */
};
static uint8_t asn_MAP_MBMSInformation_mmap_1[(11 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5)
};
static asn_SET_specifics_t asn_SPC_MBMSInformation_specs_1 = {
	sizeof(struct MBMSInformation),
	offsetof(struct MBMSInformation, _asn_ctx),
	offsetof(struct MBMSInformation, _presence_map),
	asn_MAP_MBMSInformation_tag2el_1,
	11,	/* Count of tags in the map */
	asn_MAP_MBMSInformation_tag2el_1,	/* Same as above */
	11,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_MBMSInformation_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_MBMSInformation = {
	"MBMSInformation",
	"MBMSInformation",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_MBMSInformation_tags_1,
	sizeof(asn_DEF_MBMSInformation_tags_1)
		/sizeof(asn_DEF_MBMSInformation_tags_1[0]), /* 1 */
	asn_DEF_MBMSInformation_tags_1,	/* Same as above */
	sizeof(asn_DEF_MBMSInformation_tags_1)
		/sizeof(asn_DEF_MBMSInformation_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_MBMSInformation_1,
	11,	/* Elements count */
	&asn_SPC_MBMSInformation_specs_1	/* Additional specs */
};

