/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_MBMSUserServiceType_H_
#define	_MBMSUserServiceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBMSUserServiceType {
	MBMSUserServiceType_dOWNLOAD	= 0,
	MBMSUserServiceType_sTREAMING	= 1
} e_MBMSUserServiceType;

/* MBMSUserServiceType */
typedef long	 MBMSUserServiceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MBMSUserServiceType;
asn_struct_free_f MBMSUserServiceType_free;
asn_struct_print_f MBMSUserServiceType_print;
asn_constr_check_f MBMSUserServiceType_constraint;
ber_type_decoder_f MBMSUserServiceType_decode_ber;
der_type_encoder_f MBMSUserServiceType_encode_der;
xer_type_decoder_f MBMSUserServiceType_decode_xer;
xer_type_encoder_f MBMSUserServiceType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _MBMSUserServiceType_H_ */
#include <asn_internal.h>
