/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_NodeAddress_H_
#define	_NodeAddress_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IPAddress.h"
#include <GraphicString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NodeAddress_PR {
	NodeAddress_PR_NOTHING,	/* No components present */
	NodeAddress_PR_iPAddress,
	NodeAddress_PR_domainName
} NodeAddress_PR;

/* NodeAddress */
typedef struct NodeAddress {
	NodeAddress_PR present;
	union NodeAddress_u {
		IPAddress_t	 iPAddress;
		GraphicString_t	 domainName;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NodeAddress_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NodeAddress;

#ifdef __cplusplus
}
#endif

#endif	/* _NodeAddress_H_ */
#include <asn_internal.h>
