/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_PrivateExtensionList_H_
#define	_PrivateExtensionList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PrivateExtension.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PrivateExtensionList */
typedef struct PrivateExtensionList {
	A_SEQUENCE_OF(PrivateExtension_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PrivateExtensionList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PrivateExtensionList;

#ifdef __cplusplus
}
#endif

#endif	/* _PrivateExtensionList_H_ */
#include <asn_internal.h>
