/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_RequiredMBMSBearerCapabilities_H_
#define	_RequiredMBMSBearerCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RequiredMBMSBearerCapabilities */
typedef OCTET_STRING_t	 RequiredMBMSBearerCapabilities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RequiredMBMSBearerCapabilities;
asn_struct_free_f RequiredMBMSBearerCapabilities_free;
asn_struct_print_f RequiredMBMSBearerCapabilities_print;
asn_constr_check_f RequiredMBMSBearerCapabilities_constraint;
ber_type_decoder_f RequiredMBMSBearerCapabilities_decode_ber;
der_type_encoder_f RequiredMBMSBearerCapabilities_encode_der;
xer_type_decoder_f RequiredMBMSBearerCapabilities_decode_xer;
xer_type_encoder_f RequiredMBMSBearerCapabilities_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RequiredMBMSBearerCapabilities_H_ */
#include <asn_internal.h>
