/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#include "SGSNPDPRecord.h"

static asn_TYPE_member_t asn_MBR_listOfTrafficVolumes_16[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ChangeOfCharCondition,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		""
		},
};
static ber_tlv_tag_t asn_DEF_listOfTrafficVolumes_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_listOfTrafficVolumes_specs_16 = {
	sizeof(struct SGSNPDPRecord__listOfTrafficVolumes),
	offsetof(struct SGSNPDPRecord__listOfTrafficVolumes, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listOfTrafficVolumes_16 = {
	"listOfTrafficVolumes",
	"listOfTrafficVolumes",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_listOfTrafficVolumes_tags_16,
	sizeof(asn_DEF_listOfTrafficVolumes_tags_16)
		/sizeof(asn_DEF_listOfTrafficVolumes_tags_16[0]) - 1, /* 1 */
	asn_DEF_listOfTrafficVolumes_tags_16,	/* Same as above */
	sizeof(asn_DEF_listOfTrafficVolumes_tags_16)
		/sizeof(asn_DEF_listOfTrafficVolumes_tags_16[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_listOfTrafficVolumes_16,
	1,	/* Single element */
	&asn_SPC_listOfTrafficVolumes_specs_16	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_SGSNPDPRecord_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SGSNPDPRecord, recordType),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RecordType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordType"
		},
	{ ATF_POINTER, 8, offsetof(struct SGSNPDPRecord, networkInitiation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NetworkInitiatedPDPContext,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"networkInitiation"
		},
	{ ATF_POINTER, 7, offsetof(struct SGSNPDPRecord, servedIMSI),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedIMSI"
		},
	{ ATF_POINTER, 6, offsetof(struct SGSNPDPRecord, servedIMEI),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMEI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedIMEI"
		},
	{ ATF_POINTER, 5, offsetof(struct SGSNPDPRecord, sgsnAddress),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GSNAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sgsnAddress"
		},
	{ ATF_POINTER, 4, offsetof(struct SGSNPDPRecord, msNetworkCapability),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MSNetworkCapability,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"msNetworkCapability"
		},
	{ ATF_POINTER, 3, offsetof(struct SGSNPDPRecord, routingArea),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoutingAreaCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"routingArea"
		},
	{ ATF_POINTER, 2, offsetof(struct SGSNPDPRecord, locationAreaCode),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocationAreaCode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"locationAreaCode"
		},
	{ ATF_POINTER, 1, offsetof(struct SGSNPDPRecord, cellIdentifier),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CellId,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cellIdentifier"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGSNPDPRecord, chargingID),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChargingID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargingID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGSNPDPRecord, ggsnAddressUsed),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GSNAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"ggsnAddressUsed"
		},
	{ ATF_POINTER, 4, offsetof(struct SGSNPDPRecord, accessPointNameNI),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccessPointNameNI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessPointNameNI"
		},
	{ ATF_POINTER, 3, offsetof(struct SGSNPDPRecord, pdpType),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDPType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"pdpType"
		},
	{ ATF_POINTER, 2, offsetof(struct SGSNPDPRecord, servedPDPAddress),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PDPAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedPDPAddress"
		},
	{ ATF_POINTER, 1, offsetof(struct SGSNPDPRecord, listOfTrafficVolumes),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		0,
		&asn_DEF_listOfTrafficVolumes_16,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"listOfTrafficVolumes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGSNPDPRecord, recordOpeningTime),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeStamp,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordOpeningTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGSNPDPRecord, duration),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CallDuration,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"duration"
		},
	{ ATF_POINTER, 1, offsetof(struct SGSNPDPRecord, sgsnChange),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SGSNChange,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"sgsnChange"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGSNPDPRecord, causeForRecClosing),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CauseForRecClosing,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"causeForRecClosing"
		},
	{ ATF_POINTER, 8, offsetof(struct SGSNPDPRecord, diagnostics),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Diagnostics,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"diagnostics"
		},
	{ ATF_POINTER, 7, offsetof(struct SGSNPDPRecord, recordSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordSequenceNumber"
		},
	{ ATF_POINTER, 6, offsetof(struct SGSNPDPRecord, nodeID),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeID,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"nodeID"
		},
	{ ATF_POINTER, 5, offsetof(struct SGSNPDPRecord, recordExtensions),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ManagementExtensions,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"recordExtensions"
		},
	{ ATF_POINTER, 4, offsetof(struct SGSNPDPRecord, localSequenceNumber),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalSequenceNumber,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"localSequenceNumber"
		},
	{ ATF_POINTER, 3, offsetof(struct SGSNPDPRecord, apnSelectionMode),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_APNSelectionMode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"apnSelectionMode"
		},
	{ ATF_POINTER, 2, offsetof(struct SGSNPDPRecord, accessPointNameOI),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AccessPointNameOI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"accessPointNameOI"
		},
	{ ATF_POINTER, 1, offsetof(struct SGSNPDPRecord, servedMSISDN),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MSISDN,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedMSISDN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGSNPDPRecord, chargingCharacteristics),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChargingCharacteristics,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chargingCharacteristics"
		},
	{ ATF_POINTER, 9, offsetof(struct SGSNPDPRecord, rATType),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RATType,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rATType"
		},
	{ ATF_POINTER, 8, offsetof(struct SGSNPDPRecord, cAMELInformationPDP),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CAMELInformationPDP,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"cAMELInformationPDP"
		},
	{ ATF_POINTER, 7, offsetof(struct SGSNPDPRecord, rNCUnsentDownlinkVolume),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DataVolumeGPRS,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"rNCUnsentDownlinkVolume"
		},
	{ ATF_POINTER, 6, offsetof(struct SGSNPDPRecord, chChSelectionMode),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ChChSelectionMode,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"chChSelectionMode"
		},
	{ ATF_POINTER, 5, offsetof(struct SGSNPDPRecord, dynamicAddressFlag),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DynamicAddressFlag,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"dynamicAddressFlag"
		},
	{ ATF_POINTER, 4, offsetof(struct SGSNPDPRecord, iMSIunauthenticatedFlag),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"iMSIunauthenticatedFlag"
		},
	{ ATF_POINTER, 3, offsetof(struct SGSNPDPRecord, userCSGInformation),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UserCSGInformation,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"userCSGInformation"
		},
	{ ATF_POINTER, 2, offsetof(struct SGSNPDPRecord, servedPDPPDNAddressExt),
		(ASN_TAG_CLASS_CONTEXT | (36 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_PDPAddress,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"servedPDPPDNAddressExt"
		},
	{ ATF_POINTER, 1, offsetof(struct SGSNPDPRecord, lowPriorityIndicator),
		(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"lowPriorityIndicator"
		},
};
static ber_tlv_tag_t asn_DEF_SGSNPDPRecord_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_SGSNPDPRecord_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* recordType */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* networkInitiation */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* servedIMSI */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* servedIMEI */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* sgsnAddress */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 }, /* msNetworkCapability */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 6, 0, 0 }, /* routingArea */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* locationAreaCode */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 8, 0, 0 }, /* cellIdentifier */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 9, 0, 0 }, /* chargingID */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 10, 0, 0 }, /* ggsnAddressUsed */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 11, 0, 0 }, /* accessPointNameNI */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 12, 0, 0 }, /* pdpType */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 13, 0, 0 }, /* servedPDPAddress */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 14, 0, 0 }, /* listOfTrafficVolumes */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 15, 0, 0 }, /* recordOpeningTime */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 16, 0, 0 }, /* duration */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 17, 0, 0 }, /* sgsnChange */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 18, 0, 0 }, /* causeForRecClosing */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 19, 0, 0 }, /* diagnostics */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 20, 0, 0 }, /* recordSequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 21, 0, 0 }, /* nodeID */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 22, 0, 0 }, /* recordExtensions */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 23, 0, 0 }, /* localSequenceNumber */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 24, 0, 0 }, /* apnSelectionMode */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 25, 0, 0 }, /* accessPointNameOI */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 26, 0, 0 }, /* servedMSISDN */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 27, 0, 0 }, /* chargingCharacteristics */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 28, 0, 0 }, /* rATType */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 29, 0, 0 }, /* cAMELInformationPDP */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 30, 0, 0 }, /* rNCUnsentDownlinkVolume */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 31, 0, 0 }, /* chChSelectionMode */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 32, 0, 0 }, /* dynamicAddressFlag */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 33, 0, 0 }, /* iMSIunauthenticatedFlag */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 34, 0, 0 }, /* userCSGInformation */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 35, 0, 0 }, /* servedPDPPDNAddressExt */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 36, 0, 0 } /* lowPriorityIndicator */
};
static uint8_t asn_MAP_SGSNPDPRecord_mmap_1[(37 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (1 << 6) | (1 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (1 << 0),
	(1 << 7) | (0 << 6) | (1 << 5) | (0 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5) | (1 << 4) | (0 << 3) | (0 << 2) | (0 << 1) | (0 << 0),
	(0 << 7) | (0 << 6) | (0 << 5) | (0 << 4) | (0 << 3)
};
static asn_SET_specifics_t asn_SPC_SGSNPDPRecord_specs_1 = {
	sizeof(struct SGSNPDPRecord),
	offsetof(struct SGSNPDPRecord, _asn_ctx),
	offsetof(struct SGSNPDPRecord, _presence_map),
	asn_MAP_SGSNPDPRecord_tag2el_1,
	37,	/* Count of tags in the map */
	asn_MAP_SGSNPDPRecord_tag2el_1,	/* Same as above */
	37,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(unsigned int *)asn_MAP_SGSNPDPRecord_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_SGSNPDPRecord = {
	"SGSNPDPRecord",
	"SGSNPDPRecord",
	SET_free,
	SET_print,
	SET_constraint,
	SET_decode_ber,
	SET_encode_der,
	SET_decode_xer,
	SET_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_SGSNPDPRecord_tags_1,
	sizeof(asn_DEF_SGSNPDPRecord_tags_1)
		/sizeof(asn_DEF_SGSNPDPRecord_tags_1[0]), /* 1 */
	asn_DEF_SGSNPDPRecord_tags_1,	/* Same as above */
	sizeof(asn_DEF_SGSNPDPRecord_tags_1)
		/sizeof(asn_DEF_SGSNPDPRecord_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_SGSNPDPRecord_1,
	37,	/* Elements count */
	&asn_SPC_SGSNPDPRecord_specs_1	/* Additional specs */
};

