/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#ifndef	_SGWRecord_H_
#define	_SGWRecord_H_


#include <asn_application.h>

/* Including external dependencies */
#include "RecordType.h"
#include "IMSI.h"
#include "GSNAddress.h"
#include "ChargingID.h"
#include "AccessPointNameNI.h"
#include "PDPType.h"
#include "DynamicAddressFlag.h"
#include "TimeStamp.h"
#include "CallDuration.h"
#include "CauseForRecClosing.h"
#include <NativeInteger.h>
#include "NodeID.h"
#include "LocalSequenceNumber.h"
#include "APNSelectionMode.h"
#include "MSISDN.h"
#include "ChargingCharacteristics.h"
#include "ChChSelectionMode.h"
#include <NULL.h>
#include "PLMN-Id.h"
#include "IMEI.h"
#include "RATType.h"
#include "MSTimeZone.h"
#include <OCTET_STRING.h>
#include "SGWChange.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "ServingNodeType.h"
#include <constr_SET.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */

/*
 * Method of determining the components presence
 */
typedef enum SGWRecord_PR {
	SGWRecord_PR_recordType,	/* Member recordType is present */
	SGWRecord_PR_servedIMSI,	/* Member servedIMSI is present */
	SGWRecord_PR_s_GWAddress,	/* Member s_GWAddress is present */
	SGWRecord_PR_chargingID,	/* Member chargingID is present */
	SGWRecord_PR_servingNodeAddress,	/* Member servingNodeAddress is present */
	SGWRecord_PR_accessPointNameNI,	/* Member accessPointNameNI is present */
	SGWRecord_PR_pdpPDNType,	/* Member pdpPDNType is present */
	SGWRecord_PR_servedPDPPDNAddress,	/* Member servedPDPPDNAddress is present */
	SGWRecord_PR_dynamicAddressFlag,	/* Member dynamicAddressFlag is present */
	SGWRecord_PR_listOfTrafficVolumes,	/* Member listOfTrafficVolumes is present */
	SGWRecord_PR_recordOpeningTime,	/* Member recordOpeningTime is present */
	SGWRecord_PR_duration,	/* Member duration is present */
	SGWRecord_PR_causeForRecClosing,	/* Member causeForRecClosing is present */
	SGWRecord_PR_diagnostics,	/* Member diagnostics is present */
	SGWRecord_PR_recordSequenceNumber,	/* Member recordSequenceNumber is present */
	SGWRecord_PR_nodeID,	/* Member nodeID is present */
	SGWRecord_PR_recordExtensions,	/* Member recordExtensions is present */
	SGWRecord_PR_localSequenceNumber,	/* Member localSequenceNumber is present */
	SGWRecord_PR_apnSelectionMode,	/* Member apnSelectionMode is present */
	SGWRecord_PR_servedMSISDN,	/* Member servedMSISDN is present */
	SGWRecord_PR_chargingCharacteristics,	/* Member chargingCharacteristics is present */
	SGWRecord_PR_chChSelectionMode,	/* Member chChSelectionMode is present */
	SGWRecord_PR_iMSsignalingContext,	/* Member iMSsignalingContext is present */
	SGWRecord_PR_servingNodePLMNIdentifier,	/* Member servingNodePLMNIdentifier is present */
	SGWRecord_PR_servedIMEISV,	/* Member servedIMEISV is present */
	SGWRecord_PR_rATType,	/* Member rATType is present */
	SGWRecord_PR_mSTimeZone,	/* Member mSTimeZone is present */
	SGWRecord_PR_userLocationInformation,	/* Member userLocationInformation is present */
	SGWRecord_PR_sGWChange,	/* Member sGWChange is present */
	SGWRecord_PR_servingNodeType,	/* Member servingNodeType is present */
	SGWRecord_PR_p_GWAddressUsed,	/* Member p_GWAddressUsed is present */
	SGWRecord_PR_p_GWPLMNIdentifier,	/* Member p_GWPLMNIdentifier is present */
	SGWRecord_PR_startTime,	/* Member startTime is present */
	SGWRecord_PR_stopTime,	/* Member stopTime is present */
	SGWRecord_PR_pDNConnectionChargingID,	/* Member pDNConnectionChargingID is present */
	SGWRecord_PR_iMSIunauthenticatedFlag,	/* Member iMSIunauthenticatedFlag is present */
	SGWRecord_PR_userCSGInformation,	/* Member userCSGInformation is present */
	SGWRecord_PR_servedPDPPDNAddressExt,	/* Member servedPDPPDNAddressExt is present */
	SGWRecord_PR_lowPriorityIndicator,	/* Member lowPriorityIndicator is present */
	SGWRecord_PR_dynamicAddressFlagExt,	/* Member dynamicAddressFlagExt is present */
	SGWRecord_PR_s_GWiPv6Address,	/* Member s_GWiPv6Address is present */
	SGWRecord_PR_servingNodeiPv6Address,	/* Member servingNodeiPv6Address is present */
	SGWRecord_PR_p_GWiPv6AddressUsed,	/* Member p_GWiPv6AddressUsed is present */
} SGWRecord_PR;

/* Forward declarations */
struct PDPAddress;
struct Diagnostics;
struct ManagementExtensions;
struct IPAddress;
struct UserCSGInformation;
struct ChangeOfCharCondition;

/* SGWRecord */
typedef struct SGWRecord {
	RecordType_t	 recordType;
	IMSI_t	*servedIMSI	/* OPTIONAL */;
	GSNAddress_t	 s_GWAddress;
	ChargingID_t	 chargingID;
	struct SGWRecord__servingNodeAddress {
		A_SEQUENCE_OF(struct IPAddress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} servingNodeAddress;
	AccessPointNameNI_t	*accessPointNameNI	/* OPTIONAL */;
	PDPType_t	*pdpPDNType	/* OPTIONAL */;
	struct PDPAddress	*servedPDPPDNAddress	/* OPTIONAL */;
	DynamicAddressFlag_t	*dynamicAddressFlag	/* OPTIONAL */;
	struct SGWRecord__listOfTrafficVolumes {
		A_SEQUENCE_OF(struct ChangeOfCharCondition) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *listOfTrafficVolumes;
	TimeStamp_t	 recordOpeningTime;
	CallDuration_t	 duration;
	CauseForRecClosing_t	 causeForRecClosing;
	struct Diagnostics	*diagnostics	/* OPTIONAL */;
	long	*recordSequenceNumber	/* OPTIONAL */;
	NodeID_t	*nodeID	/* OPTIONAL */;
	struct ManagementExtensions	*recordExtensions	/* OPTIONAL */;
	LocalSequenceNumber_t	*localSequenceNumber	/* OPTIONAL */;
	APNSelectionMode_t	*apnSelectionMode	/* OPTIONAL */;
	MSISDN_t	*servedMSISDN	/* OPTIONAL */;
	ChargingCharacteristics_t	 chargingCharacteristics;
	ChChSelectionMode_t	*chChSelectionMode	/* OPTIONAL */;
	NULL_t	*iMSsignalingContext	/* OPTIONAL */;
	PLMN_Id_t	*servingNodePLMNIdentifier	/* OPTIONAL */;
	IMEI_t	*servedIMEISV	/* OPTIONAL */;
	RATType_t	*rATType	/* OPTIONAL */;
	MSTimeZone_t	*mSTimeZone	/* OPTIONAL */;
	OCTET_STRING_t	*userLocationInformation	/* OPTIONAL */;
	SGWChange_t	*sGWChange	/* OPTIONAL */;
	struct SGWRecord__servingNodeType {
		A_SEQUENCE_OF(ServingNodeType_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} servingNodeType;
	struct IPAddress	*p_GWAddressUsed	/* OPTIONAL */;
	PLMN_Id_t	*p_GWPLMNIdentifier	/* OPTIONAL */;
	TimeStamp_t	*startTime	/* OPTIONAL */;
	TimeStamp_t	*stopTime	/* OPTIONAL */;
	ChargingID_t	*pDNConnectionChargingID	/* OPTIONAL */;
	NULL_t	*iMSIunauthenticatedFlag	/* OPTIONAL */;
	struct UserCSGInformation	*userCSGInformation	/* OPTIONAL */;
	struct PDPAddress	*servedPDPPDNAddressExt	/* OPTIONAL */;
	NULL_t	*lowPriorityIndicator	/* OPTIONAL */;
	DynamicAddressFlag_t	*dynamicAddressFlagExt	/* OPTIONAL */;
	struct IPAddress	*s_GWiPv6Address	/* OPTIONAL */;
	struct SGWRecord__servingNodeiPv6Address {
		A_SEQUENCE_OF(struct IPAddress) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *servingNodeiPv6Address;
	struct IPAddress	*p_GWiPv6AddressUsed	/* OPTIONAL */;
	
	/* Presence bitmask: ASN_SET_ISPRESENT(pSGWRecord, SGWRecord_PR_x) */
	unsigned int _presence_map
		[((43+(8*sizeof(unsigned int))-1)/(8*sizeof(unsigned int)))];
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGWRecord_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGWRecord;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDPAddress.h"
#include "Diagnostics.h"
#include "ManagementExtensions.h"
#include "GSNAddress.h"
#include "UserCSGInformation.h"
#include "ChangeOfCharCondition.h"

#endif	/* _SGWRecord_H_ */
#include <asn_internal.h>
