/*
 * Generated by asn1c-0.9.27 (http://lionet.info/asn1c)
 * From ASN.1 module "GPRSChargingDataTypesV1171"
 * 	found in "../GPRSChargingDataTypesV1171_py_asn1c_2.asn"
 */

#include "SubscriberId.h"

static asn_TYPE_member_t asn_MBR_SubscriberId_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriberId, choice.imsi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imsi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SubscriberId, choice.tmsi),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TMSI,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"tmsi"
		},
};
static asn_TYPE_tag2member_t asn_MAP_SubscriberId_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* imsi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* tmsi */
};
static asn_CHOICE_specifics_t asn_SPC_SubscriberId_specs_1 = {
	sizeof(struct SubscriberId),
	offsetof(struct SubscriberId, _asn_ctx),
	offsetof(struct SubscriberId, present),
	sizeof(((struct SubscriberId *)0)->present),
	asn_MAP_SubscriberId_tag2el_1,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SubscriberId = {
	"SubscriberId",
	"SubscriberId",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_SubscriberId_1,
	2,	/* Elements count */
	&asn_SPC_SubscriberId_specs_1	/* Additional specs */
};

