# Auto-generated by asn1ate v.0.5.1.dev from GPRSChargingDataTypesV1171_py.asn
# (last modified on 2016-08-16 10:23:26.272852)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class AFChargingIdentifier(univ.OctetString):
    pass


class Flows(univ.Sequence):
    pass


Flows.componentType = namedtype.NamedTypes(
    namedtype.NamedType('mediaComponentNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('flowNumber', univ.SequenceOf(componentType=univ.Integer()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


class AFRecordInformation(univ.Sequence):
    pass


AFRecordInformation.componentType = namedtype.NamedTypes(
    namedtype.NamedType('aFChargingIdentifier', AFChargingIdentifier().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('flows', Flows().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 2)))
)


class APNSelectionMode(univ.Enumerated):
    pass


APNSelectionMode.namedValues = namedval.NamedValues(
    ('mSorNetworkProvidedSubscriptionVerified', 0),
    ('mSProvidedSubscriptionNotVerified', 1),
    ('networkProvidedSubscriptionNotVerified', 2)
)


class TBCD_STRING(univ.OctetString):
    pass


class ASCI_CallReference(TBCD_STRING):
    pass


class AccessPointNameNI(char.IA5String):
    pass


AccessPointNameNI.subtypeSpec = constraint.ValueSizeConstraint(1, 63)


class AccessPointNameOI(char.IA5String):
    pass


AccessPointNameOI.subtypeSpec = constraint.ValueSizeConstraint(1, 37)


maxAddressLength = univ.Integer(20)


class AddressString(univ.OctetString):
    pass


AddressString.subtypeSpec = constraint.ValueSizeConstraint(1, maxAddressLength)


class BCDDirectoryNumber(univ.OctetString):
    pass


class BearerServiceCode(univ.OctetString):
    pass


BearerServiceCode.subtypeSpec = constraint.ValueSizeConstraint(1, 1)


class CAMELAccessPointNameNI(AccessPointNameNI):
    pass


class CAMELAccessPointNameOI(AccessPointNameOI):
    pass


class DefaultGPRS_Handling(univ.Enumerated):
    pass


DefaultGPRS_Handling.namedValues = namedval.NamedValues(
    ('continueTransaction', 0),
    ('releaseTransaction', 1)
)


class FreeFormatData(univ.OctetString):
    pass


FreeFormatData.subtypeSpec = constraint.ValueSizeConstraint(1, 160)


class NumberOfDPEncountered(univ.Integer):
    pass


class FFDAppendIndicator(univ.Boolean):
    pass


class LevelOfCAMELService(univ.BitString):
    pass


LevelOfCAMELService.namedValues = namedval.NamedValues(
    ('basic', 0),
    ('callDurationSupervision', 1),
    ('onlineCharging', 2)
)


class ServiceKey(univ.Integer):
    pass


ServiceKey.subtypeSpec = constraint.ValueRangeConstraint(0, 2147483647)


class SCFAddress(AddressString):
    pass


class CAMELInformationMM(univ.Set):
    pass


CAMELInformationMM.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('sCFAddress', SCFAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('serviceKey', ServiceKey().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('defaultTransactionHandling', DefaultGPRS_Handling().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('numberOfDPEncountered', NumberOfDPEncountered().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('levelOfCAMELService', LevelOfCAMELService().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('freeFormatData', FreeFormatData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('fFDAppendIndicator', FFDAppendIndicator().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7)))
)


class CAMELInformationPDP(univ.Set):
    pass


CAMELInformationPDP.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('sCFAddress', SCFAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('serviceKey', ServiceKey().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('defaultTransactionHandling', DefaultGPRS_Handling().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('cAMELAccessPointNameNI', CAMELAccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('cAMELAccessPointNameOI', CAMELAccessPointNameOI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('numberOfDPEncountered', NumberOfDPEncountered().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('levelOfCAMELService', LevelOfCAMELService().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('freeFormatData', FreeFormatData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('fFDAppendIndicator', FFDAppendIndicator().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9)))
)


class CallReferenceNumber(univ.OctetString):
    pass


CallReferenceNumber.subtypeSpec = constraint.ValueSizeConstraint(1, 8)


class SmsTpDestinationNumber(univ.OctetString):
    pass


class CallingNumber(BCDDirectoryNumber):
    pass


class DefaultSMS_Handling(univ.Enumerated):
    pass


DefaultSMS_Handling.namedValues = namedval.NamedValues(
    ('continueTransaction', 0),
    ('releaseTransaction', 1)
)


class CAMELInformationSMS(univ.Set):
    pass


CAMELInformationSMS.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('sCFAddress', SCFAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('serviceKey', ServiceKey().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('defaultSMSHandling', DefaultSMS_Handling().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('cAMELCallingPartyNumber', CallingNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('cAMELDestinationSubscriberNumber', SmsTpDestinationNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('cAMELSMSCAddress', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('freeFormatData', FreeFormatData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('smsReferenceNumber', CallReferenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8)))
)


class CNIPMulticastDistribution(univ.Enumerated):
    pass


CNIPMulticastDistribution.namedValues = namedval.NamedValues(
    ('nO-IP-MULTICAST', 0),
    ('iP-MULTICAST', 1)
)


class CSGAccessMode(univ.Enumerated):
    pass


CSGAccessMode.namedValues = namedval.NamedValues(
    ('closedMode', 0),
    ('hybridMode', 1)
)


class CSGId(univ.OctetString):
    pass


CSGId.subtypeSpec = constraint.ValueSizeConstraint(4, 4)


class CTEID(univ.OctetString):
    pass


CTEID.subtypeSpec = constraint.ValueSizeConstraint(4, 4)


class CallDuration(univ.Integer):
    pass


class CallEventRecordType(univ.Integer):
    pass


CallEventRecordType.namedValues = namedval.NamedValues(
    ('moCallRecord', 0),
    ('mtCallRecord', 1),
    ('roamingRecord', 2),
    ('incGatewayRecord', 3),
    ('outGatewayRecord', 4),
    ('transitCallRecord', 5),
    ('moSMSRecord', 6),
    ('mtSMSRecord', 7),
    ('moSMSIWRecord', 8),
    ('mtSMSGWRecord', 9),
    ('ssActionRecord', 10),
    ('hlrIntRecord', 11),
    ('locUpdateHLRRecord', 12),
    ('locUpdateVLRRecord', 13),
    ('commonEquipRecord', 14),
    ('moTraceRecord', 15),
    ('mtTraceRecord', 16),
    ('termCAMELRecord', 17),
    ('sgsnPDPRecord', 18),
    ('ggsnPDPRecord', 19),
    ('sgsnMMRecord', 20),
    ('sgsnSMORecord', 21),
    ('sgsnSMTRecord', 22),
    ('mtLCSRecord', 23),
    ('moLCSRecord', 24),
    ('niLCSRecord', 25),
    ('sgsnMtLCSRecord', 26),
    ('sgsnMoLCSRecord', 27),
    ('sgsnNiLCSRecord', 28),
    ('mmO1SRecord', 29),
    ('mmO4FRqRecord', 30),
    ('mmO4FRsRecord', 31),
    ('mmO4DRecord', 32),
    ('mmO1DRecord', 33),
    ('mmO4RRecord', 34),
    ('mmO1RRecord', 35),
    ('mmOMDRecord', 36),
    ('mmR4FRecord', 37),
    ('mmR1NRqRecord', 38),
    ('mmR1NRsRecord', 39),
    ('mmR1RtRecord', 40),
    ('mmR1AFRecord', 42),
    ('mmR4DRqRecord', 43),
    ('mmR4DRsRecord', 44),
    ('mmR1RRRecord', 45),
    ('mmR4RRqRecord', 46),
    ('mmR4RRsRecord', 47),
    ('mmRMDRecord', 48),
    ('mmFRecord', 49),
    ('mmBx1SRecord', 50),
    ('mmBx1VRecord', 51),
    ('mmBx1URecord', 52),
    ('mmBx1DRecord', 53),
    ('mM7SRecord', 54),
    ('mM7DRqRecord', 55),
    ('mM7DRsRecord', 56),
    ('mM7CRecord', 57),
    ('mM7RRecord', 58),
    ('mM7DRRqRecord', 59),
    ('mM7DRRsRecord', 60),
    ('mM7RRqRecord', 61),
    ('mM7RRsRecord', 62),
    ('s-CSCFRecord', 63),
    ('p-CSCFRecord', 64),
    ('i-CSCFRecord', 65),
    ('mRFCRecord', 66),
    ('mGCFRecord', 67),
    ('bGCFRecord', 68),
    ('aSRecord', 69),
    ('egsnPDPRecord', 70),
    ('lCSGMORecord', 71),
    ('lCSRGMTRecord', 72),
    ('lCSHGMTRecord', 73),
    ('lCSVGMTRecord', 74),
    ('lCSGNIRecord', 75),
    ('sgsnMBMSRecord', 76),
    ('ggsnMBMSRecord', 77),
    ('subBMSCRecord', 78),
    ('contentBMSCRecord', 79),
    ('pPFRecord', 80),
    ('cPFRecord', 81)
)


class CalledNumber(BCDDirectoryNumber):
    pass


class CauseForRecClosing(univ.Integer):
    pass


CauseForRecClosing.namedValues = namedval.NamedValues(
    ('normalRelease', 0),
    ('abnormalRelease', 4),
    ('cAMELInitCallRelease', 5),
    ('volumeLimit', 16),
    ('timeLimit', 17),
    ('servingNodeChange', 18),
    ('maxChangeCond', 19),
    ('managementIntervention', 20),
    ('intraSGSNIntersystemChange', 21),
    ('rATChange', 22),
    ('mSTimeZoneChange', 23),
    ('sGSNPLMNIDChange', 24),
    ('unauthorizedRequestingNetwork', 52),
    ('unauthorizedLCSClient', 53),
    ('positionMethodFailure', 54),
    ('unknownOrUnreachableLCSClient', 58),
    ('listofDownstreamNodeChange', 59)
)


class CellId(univ.OctetString):
    pass


CellId.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class ChChSelectionMode(univ.Enumerated):
    pass


ChChSelectionMode.namedValues = namedval.NamedValues(
    ('servingNodeSupplied', 0),
    ('subscriptionSpecific', 1),
    ('aPNSpecific', 2),
    ('homeDefault', 3),
    ('roamingDefault', 4),
    ('visitingDefault', 5)
)


class ChangeCondition(univ.Enumerated):
    pass


ChangeCondition.namedValues = namedval.NamedValues(
    ('qoSChange', 0),
    ('tariffTime', 1),
    ('recordClosure', 2),
    ('cGI-SAICHange', 6),
    ('rAIChange', 7),
    ('dT-Establishment', 8),
    ('dT-Removal', 9),
    ('eCGIChange', 10),
    ('tAIChange', 11),
    ('userLocationChange', 12)
)


class TimeStamp(univ.OctetString):
    pass


TimeStamp.subtypeSpec = constraint.ValueSizeConstraint(9, 9)


class PLMN_Id(univ.OctetString):
    pass


PLMN_Id.subtypeSpec = constraint.ValueSizeConstraint(3, 3)


class RoutingAreaCode(univ.OctetString):
    pass


RoutingAreaCode.subtypeSpec = constraint.ValueSizeConstraint(1, 1)


class LocationAreaCode(univ.OctetString):
    pass


LocationAreaCode.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class ChangeLocation(univ.Sequence):
    pass


ChangeLocation.componentType = namedtype.NamedTypes(
    namedtype.NamedType('locationAreaCode', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('routingAreaCode', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('cellId', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('changeTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('mCC-MNC', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4)))
)


class QoSInformation(univ.OctetString):
    pass


QoSInformation.subtypeSpec = constraint.ValueSizeConstraint(4, 255)


class EPCQoSInformation(univ.Sequence):
    pass


EPCQoSInformation.componentType = namedtype.NamedTypes(
    namedtype.NamedType('qCI', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('maxRequestedBandwithUL', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('maxRequestedBandwithDL', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('guaranteedBitrateUL', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('guaranteedBitrateDL', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('aRP', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('aPNAggregateMaxBitrateUL', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('aPNAggregateMaxBitrateDL', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8)))
)


class DataVolumeGPRS(univ.Integer):
    pass


class ChangeOfCharCondition(univ.Sequence):
    pass


ChangeOfCharCondition.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('qosRequested', QoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('qosNegotiated', QoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('dataVolumeGPRSUplink', DataVolumeGPRS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('dataVolumeGPRSDownlink', DataVolumeGPRS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.NamedType('changeCondition', ChangeCondition().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.NamedType('changeTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('userLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('ePCQoSInformation', EPCQoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 9)))
)


class FailureHandlingContinue(univ.Boolean):
    pass


class DataVolumeMBMS(univ.Integer):
    pass


class ChangeOfMBMSCondition(univ.Sequence):
    pass


ChangeOfMBMSCondition.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('qosRequested', QoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('qosNegotiated', QoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('dataVolumeMBMSUplink', DataVolumeMBMS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.NamedType('dataVolumeMBMSDownlink', DataVolumeMBMS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.NamedType('changeCondition', ChangeCondition().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.NamedType('changeTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('failureHandlingContinue', FailureHandlingContinue().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7)))
)


class ChargingRuleBaseName(char.IA5String):
    pass


class LocalSequenceNumber(univ.Integer):
    pass


LocalSequenceNumber.subtypeSpec = constraint.ValueRangeConstraint(0, 4294967295)


class ResultCode(univ.Integer):
    pass


class ServiceConditionChange(univ.BitString):
    pass


ServiceConditionChange.namedValues = namedval.NamedValues(
    ('qoSChange', 0),
    ('sGSNChange', 1),
    ('sGSNPLMNIDChange', 2),
    ('tariffTimeSwitch', 3),
    ('pDPContextRelease', 4),
    ('rATChange', 5),
    ('serviceIdledOut', 6),
    ('reserved', 7),
    ('configurationChange', 8),
    ('serviceStop', 9),
    ('dCCATimeThresholdReached', 10),
    ('dCCAVolumeThresholdReached', 11),
    ('dCCAServiceSpecificUnitThresholdReached', 12),
    ('dCCATimeExhausted', 13),
    ('dCCAVolumeExhausted', 14),
    ('dCCAValidityTimeout', 15),
    ('reserved1', 16),
    ('dCCAReauthorisationRequest', 17),
    ('dCCAContinueOngoingSession', 18),
    ('dCCARetryAndTerminateOngoingSession', 19),
    ('dCCATerminateOngoingSession', 20),
    ('cGI-SAIChange', 21),
    ('rAIChange', 22),
    ('dCCAServiceSpecificUnitExhausted', 23),
    ('recordClosure', 24),
    ('timeLimit', 25),
    ('volumeLimit', 26),
    ('serviceSpecificUnitLimit', 27),
    ('envelopeClosure', 28),
    ('eCGIChange', 29),
    ('tAIChange', 30),
    ('userLocationChange', 31)
)


class TimeQuotaType(univ.Enumerated):
    pass


TimeQuotaType.namedValues = namedval.NamedValues(
    ('dISCRETETIMEPERIOD', 0),
    ('cONTINUOUSTIMEPERIOD', 1)
)


class TimeQuotaMechanism(univ.Sequence):
    pass


TimeQuotaMechanism.componentType = namedtype.NamedTypes(
    namedtype.NamedType('timeQuotaType', TimeQuotaType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('baseTimeInterval', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


class PSFurnishChargingInformation(univ.Sequence):
    pass


PSFurnishChargingInformation.componentType = namedtype.NamedTypes(
    namedtype.NamedType('pSFreeFormatData', FreeFormatData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('pSFFDAppendIndicator', FFDAppendIndicator().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


class EventBasedChargingInformation(univ.Sequence):
    pass


EventBasedChargingInformation.componentType = namedtype.NamedTypes(
    namedtype.NamedType('numberOfEvents', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('eventTimeStamps', univ.SequenceOf(componentType=TimeStamp()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


class IPBinV4Address(univ.OctetString):
    pass


IPBinV4Address.subtypeSpec = constraint.ValueSizeConstraint(4, 4)


class IPBinV6Address(univ.OctetString):
    pass


IPBinV6Address.subtypeSpec = constraint.ValueSizeConstraint(16, 16)


class PDPAddressPrefixLength(univ.Integer):
    pass


PDPAddressPrefixLength.subtypeSpec = constraint.ValueRangeConstraint(1, 64)


class IPBinV6AddressWithPrefixLength(univ.Sequence):
    pass


IPBinV6AddressWithPrefixLength.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPBinV6Address', IPBinV6Address()),
    namedtype.DefaultedNamedType('pDPAddressPrefixLength', PDPAddressPrefixLength().subtype(value=64))
)


class IPBinV6AddressWithOrWithoutPrefixLength(univ.Choice):
    pass


IPBinV6AddressWithOrWithoutPrefixLength.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPBinV6Address', IPBinV6Address().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('iPBinV6AddressWithPrefix', IPBinV6AddressWithPrefixLength().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 4)))
)


class IPBinaryAddress(univ.Choice):
    pass


IPBinaryAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPBinV4Address', IPBinV4Address().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('iPBinV6Address', IPBinV6AddressWithOrWithoutPrefixLength())
)


class IPTextRepresentedAddress(univ.Choice):
    pass


IPTextRepresentedAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPTextV4Address', char.IA5String().subtype(subtypeSpec=constraint.ValueSizeConstraint(7, 15)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('iPTextV6Address', char.IA5String().subtype(subtypeSpec=constraint.ValueSizeConstraint(15, 45)).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3)))
)


class IPAddress(univ.Choice):
    pass


IPAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPBinaryAddress', IPBinaryAddress()),
    namedtype.NamedType('iPTextRepresentedAddress', IPTextRepresentedAddress())
)


class GSNAddress(IPAddress):
    pass


class RatingGroupId(univ.Integer):
    pass


class ServiceIdentifier(univ.Integer):
    pass


ServiceIdentifier.subtypeSpec = constraint.ValueRangeConstraint(0, 4294967295)


class ServiceSpecificInfo(univ.Sequence):
    pass


ServiceSpecificInfo.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('serviceSpecificData', char.GraphicString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('serviceSpecificType', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class ChangeOfServiceCondition(univ.Sequence):
    pass


ChangeOfServiceCondition.componentType = namedtype.NamedTypes(
    namedtype.NamedType('ratingGroup', RatingGroupId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('chargingRuleBaseName', ChargingRuleBaseName().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('resultCode', ResultCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('timeOfFirstUsage', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('timeOfLastUsage', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('timeUsage', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.NamedType('serviceConditionChange', ServiceConditionChange().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('qoSInformationNeg', EPCQoSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 9))),
    namedtype.OptionalNamedType('servingNodeAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 10))),
    namedtype.OptionalNamedType('datavolumeFBCUplink', DataVolumeGPRS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('datavolumeFBCDownlink', DataVolumeGPRS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.NamedType('timeOfReport', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('failureHandlingContinue', FailureHandlingContinue().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('serviceIdentifier', ServiceIdentifier().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('pSFurnishChargingInformation', PSFurnishChargingInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 18))),
    namedtype.OptionalNamedType('aFRecordInformation', univ.SequenceOf(componentType=AFRecordInformation()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('userLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.OptionalNamedType('eventBasedChargingInformation', EventBasedChargingInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 21))),
    namedtype.OptionalNamedType('timeQuotaMechanism', TimeQuotaMechanism().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 22))),
    namedtype.OptionalNamedType('serviceSpecificInfo', univ.SequenceOf(componentType=ServiceSpecificInfo()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('threeGPP2UserLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('sponsorIdentity', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25))),
    namedtype.OptionalNamedType('applicationServiceProviderIdentity', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 26)))
)


class ChargeIndicator(univ.Integer):
    pass


ChargeIndicator.namedValues = namedval.NamedValues(
    ('noCharge', 0),
    ('charge', 1)
)


class ChargingCharacteristics(univ.OctetString):
    pass


ChargingCharacteristics.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class ChargingID(univ.Integer):
    pass


ChargingID.subtypeSpec = constraint.ValueRangeConstraint(0, 4294967295)


class DeferredLocationEventType(univ.BitString):
    pass


DeferredLocationEventType.namedValues = namedval.NamedValues(
    ('msAvailable', 0),
    ('enteringIntoArea', 1),
    ('leavingFromArea', 2),
    ('beingInsideArea', 3),
    ('periodicLDR', 4)
)
DeferredLocationEventType.subtypeSpec=constraint.ValueSizeConstraint(1, 16)


class ManagementExtension(univ.OctetString):
    pass


class PositionMethodFailure_Diagnostic(univ.Enumerated):
    pass


PositionMethodFailure_Diagnostic.namedValues = namedval.NamedValues(
    ('congestion', 0),
    ('insufficientResources', 1),
    ('insufficientMeasurementData', 2),
    ('inconsistentMeasurementData', 3),
    ('locationProcedureNotCompleted', 4),
    ('locationProcedureNotSupportedByTargetMS', 5),
    ('qoSNotAttainable', 6),
    ('positionMethodNotAvailableInNetwork', 7),
    ('positionMethodNotAvailableInLocationArea', 8)
)


class UnauthorizedLCSClient_Diagnostic(univ.Enumerated):
    pass


UnauthorizedLCSClient_Diagnostic.namedValues = namedval.NamedValues(
    ('noAdditionalInformation', 0),
    ('clientNotInMSPrivacyExceptionList', 1),
    ('callToClientNotSetup', 2),
    ('privacyOverrideNotApplicable', 3),
    ('disallowedByLocalRegulatoryRequirements', 4),
    ('unauthorizedPrivacyClass', 5),
    ('unauthorizedCallSessionUnrelatedExternalClient', 6),
    ('unauthorizedCallSessionRelatedExternalClient', 7)
)


class Diagnostics(univ.Choice):
    pass


Diagnostics.componentType = namedtype.NamedTypes(
    namedtype.NamedType('gsm0408Cause', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('gsm0902MapErrorValue', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('itu-tQ767Cause', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('networkSpecificCause', ManagementExtension().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.NamedType('manufacturerSpecificCause', ManagementExtension().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.NamedType('positionMethodFailureCause', PositionMethodFailure_Diagnostic().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.NamedType('unauthorizedLCSClientCause', UnauthorizedLCSClient_Diagnostic().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.NamedType('diameterResultCodeAndExperimentalResult', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7)))
)


class DiameterIdentity(univ.OctetString):
    pass


class DynamicAddressFlag(univ.Boolean):
    pass


class Ext_BearerServiceCode(univ.OctetString):
    pass


Ext_BearerServiceCode.subtypeSpec = constraint.ValueSizeConstraint(1, 5)


maxExt_GeographicalInformation = univ.Integer(20)


class Ext_GeographicalInformation(univ.OctetString):
    pass


Ext_GeographicalInformation.subtypeSpec = constraint.ValueSizeConstraint(1, maxExt_GeographicalInformation)


class PCS_Extensions(univ.Sequence):
    pass


PCS_Extensions.componentType = namedtype.NamedTypes(

)


maxNumOfPrivateExtensions = univ.Integer(10)


class PrivateExtension(univ.OctetString):
    pass


class PrivateExtensionList(univ.SequenceOf):
    pass


PrivateExtensionList.componentType = PrivateExtension()
PrivateExtensionList.subtypeSpec=constraint.ValueSizeConstraint(1, maxNumOfPrivateExtensions)


class ExtensionContainer(univ.Sequence):
    pass


ExtensionContainer.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('privateExtensionList', PrivateExtensionList().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('pcs-Extensions', PCS_Extensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1)))
)


class ManagementExtensions(univ.SetOf):
    pass


ManagementExtensions.componentType = ManagementExtension()


class TMGI(univ.OctetString):
    pass


class MBMSServiceType(univ.Enumerated):
    pass


MBMSServiceType.namedValues = namedval.NamedValues(
    ('mULTICAST', 0),
    ('bROADCAST', 1)
)


class RequiredMBMSBearerCapabilities(univ.OctetString):
    pass


RequiredMBMSBearerCapabilities.subtypeSpec = constraint.ValueSizeConstraint(3, 14)


class MBMSSessionIdentity(univ.OctetString):
    pass


MBMSSessionIdentity.subtypeSpec = constraint.ValueSizeConstraint(1, 1)


class MBMSUserServiceType(univ.Enumerated):
    pass


MBMSUserServiceType.namedValues = namedval.NamedValues(
    ('dOWNLOAD', 0),
    ('sTREAMING', 1)
)


class MBMSServiceArea(univ.OctetString):
    pass


class MBMS2G3GIndicator(univ.Enumerated):
    pass


MBMS2G3GIndicator.namedValues = namedval.NamedValues(
    ('twoG', 0),
    ('threeG', 1),
    ('twoG-AND-threeG', 2)
)


class MBMSInformation(univ.Set):
    pass


MBMSInformation.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('tMGI', TMGI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('mBMSSessionIdentity', MBMSSessionIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('mBMSServiceType', MBMSServiceType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('mBMSUserServiceType', MBMSUserServiceType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('mBMS2G3GIndicator', MBMS2G3GIndicator().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('fileRepairSupported', univ.Boolean().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('rAI', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('mBMSServiceArea', MBMSServiceArea().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('requiredMBMSBearerCaps', RequiredMBMSBearerCapabilities().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.OptionalNamedType('mBMSGWAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 10))),
    namedtype.OptionalNamedType('cNIPMulticastDistribution', CNIPMulticastDistribution().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11)))
)


class PDPAddress(univ.Choice):
    pass


PDPAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPAddress', IPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0)))
)


class NodeID(char.IA5String):
    pass


NodeID.subtypeSpec = constraint.ValueSizeConstraint(1, 20)


class RecordType(univ.Integer):
    pass


RecordType.namedValues = namedval.NamedValues(
    ('moCallRecord', 0),
    ('mtCallRecord', 1),
    ('roamingRecord', 2),
    ('incGatewayRecord', 3),
    ('outGatewayRecord', 4),
    ('transitCallRecord', 5),
    ('moSMSRecord', 6),
    ('mtSMSRecord', 7),
    ('moSMSIWRecord', 8),
    ('mtSMSGWRecord', 9),
    ('ssActionRecord', 10),
    ('hlrIntRecord', 11),
    ('locUpdateHLRRecord', 12),
    ('locUpdateVLRRecord', 13),
    ('commonEquipRecord', 14),
    ('moTraceRecord', 15),
    ('mtTraceRecord', 16),
    ('termCAMELRecord', 17),
    ('sgsnPDPRecord', 18),
    ('sgsnMMRecord', 20),
    ('sgsnSMORecord', 21),
    ('sgsnSMTRecord', 22),
    ('mtLCSRecord', 23),
    ('moLCSRecord', 24),
    ('niLCSRecord', 25),
    ('sgsnMTLCSRecord', 26),
    ('sgsnMOLCSRecord', 27),
    ('sgsnNILCSRecord', 28),
    ('mMO1SRecord', 30),
    ('mMO4FRqRecord', 31),
    ('mMO4FRsRecord', 32),
    ('mMO4DRecord', 33),
    ('mMO1DRecord', 34),
    ('mMO4RRecord', 35),
    ('mMO1RRecord', 36),
    ('mMOMDRecord', 37),
    ('mMR4FRecord', 38),
    ('mMR1NRqRecord', 39),
    ('mMR1NRsRecord', 40),
    ('mMR1RtRecord', 41),
    ('mMR1AFRecord', 42),
    ('mMR4DRqRecord', 43),
    ('mMR4DRsRecord', 44),
    ('mMR1RRRecord', 45),
    ('mMR4RRqRecord', 46),
    ('mMR4RRsRecord', 47),
    ('mMRMDRecord', 48),
    ('mMFRecord', 49),
    ('mMBx1SRecord', 50),
    ('mMBx1VRecord', 51),
    ('mMBx1URecord', 52),
    ('mMBx1DRecord', 53),
    ('mM7SRecord', 54),
    ('mM7DRqRecord', 55),
    ('mM7DRsRecord', 56),
    ('mM7CRecord', 57),
    ('mM7RRecord', 58),
    ('mM7DRRqRecord', 59),
    ('mM7DRRsRecord', 60),
    ('mM7RRqRecord', 61),
    ('mM7RRsRecord', 62),
    ('sCSCFRecord', 63),
    ('pCSCFRecord', 64),
    ('iCSCFRecord', 65),
    ('mRFCRecord', 66),
    ('mGCFRecord', 67),
    ('bGCFRecord', 68),
    ('aSRecord', 69),
    ('eCSCFRecord', 70),
    ('iBCFRecord', 82),
    ('tRFRecord', 89),
    ('tFRecord', 90),
    ('aTCFRecord', 91),
    ('lCSGMORecord', 71),
    ('lCSRGMTRecord', 72),
    ('lCSHGMTRecord', 73),
    ('lCSVGMTRecord', 74),
    ('lCSGNIRecord', 75),
    ('sgsnMBMSRecord', 76),
    ('ggsnMBMSRecord', 77),
    ('gwMBMSRecord', 86),
    ('sUBBMSCRecord', 78),
    ('cONTENTBMSCRecord', 79),
    ('pPFRecord', 80),
    ('cPFRecord', 81),
    ('sGWRecord', 84),
    ('pGWRecord', 85),
    ('mMTelRecord', 83),
    ('mSCsRVCCRecord', 87),
    ('mMTRFRecord', 88)
)


class GGSNMBMSRecord(univ.Set):
    pass


GGSNMBMSRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('ggsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1))),
    namedtype.NamedType('chargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('listofDownstreamNodes', univ.SequenceOf(componentType=GSNAddress()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('servedPDPAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 5))),
    namedtype.OptionalNamedType('listOfTrafficVolumes', univ.SequenceOf(componentType=ChangeOfMBMSCondition()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.NamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 10))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('mbmsInformation', MBMSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 15)))
)


class MSNetworkCapability(univ.OctetString):
    pass


MSNetworkCapability.subtypeSpec = constraint.ValueSizeConstraint(1, 8)


class RATType(univ.Integer):
    pass


RATType.subtypeSpec = constraint.ValueRangeConstraint(0, 255)


class IMSI(TBCD_STRING):
    pass


class SGSNChange(univ.Boolean):
    pass


class UserCSGInformation(univ.Sequence):
    pass


UserCSGInformation.componentType = namedtype.NamedTypes(
    namedtype.NamedType('cSGId', CSGId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('cSGAccessMode', CSGAccessMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('cSGMembershipIndication', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


maxISDN_AddressLength = univ.Integer(9)


class ISDN_AddressString(AddressString):
    pass


class MSISDN(ISDN_AddressString):
    pass


class PDPType(univ.OctetString):
    pass


PDPType.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class IMEI(TBCD_STRING):
    pass


class NetworkInitiatedPDPContext(univ.Boolean):
    pass


class SGSNPDPRecord(univ.Set):
    pass


SGSNPDPRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('networkInitiation', NetworkInitiatedPDPContext().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('sgsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 5))),
    namedtype.OptionalNamedType('msNetworkCapability', MSNetworkCapability().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('locationAreaCode', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('cellIdentifier', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('chargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.NamedType('ggsnAddressUsed', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 11))),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('pdpType', PDPType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('servedPDPAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 14))),
    namedtype.OptionalNamedType('listOfTrafficVolumes', univ.SequenceOf(componentType=ChangeOfCharCondition()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.NamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('sgsnChange', SGSNChange().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 20))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('apnSelectionMode', APNSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25))),
    namedtype.OptionalNamedType('accessPointNameOI', AccessPointNameOI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 26))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 27))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 28))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 29))),
    namedtype.OptionalNamedType('cAMELInformationPDP', CAMELInformationPDP().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 30))),
    namedtype.OptionalNamedType('rNCUnsentDownlinkVolume', DataVolumeGPRS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 31))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 32))),
    namedtype.OptionalNamedType('dynamicAddressFlag', DynamicAddressFlag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 33))),
    namedtype.OptionalNamedType('iMSIunauthenticatedFlag', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 34))),
    namedtype.OptionalNamedType('userCSGInformation', UserCSGInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 35))),
    namedtype.OptionalNamedType('servedPDPPDNAddressExt', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 36))),
    namedtype.OptionalNamedType('lowPriorityIndicator', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 37)))
)


class ServingNodeType(univ.Enumerated):
    pass


ServingNodeType.namedValues = namedval.NamedValues(
    ('sGSN', 0),
    ('pMIPSGW', 1),
    ('gTPSGW', 2),
    ('ePDG', 3),
    ('hSGW', 4),
    ('mME', 5),
    ('tWAN', 6)
)


class SMSResult(Diagnostics):
    pass


class MessageReference(univ.OctetString):
    pass


class RecordingEntity(AddressString):
    pass


class SGSNSMORecord(univ.Set):
    pass


SGSNSMORecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('msNetworkCapability', MSNetworkCapability().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('serviceCentre', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('recordingEntity', RecordingEntity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('locationArea', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('cellIdentifier', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('messageReference', MessageReference().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.NamedType('eventTimeStamp', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('smsResult', SMSResult().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 12))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('destinationNumber', SmsTpDestinationNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.OptionalNamedType('cAMELInformationSMS', CAMELInformationSMS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 19))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.NamedType('servingNodeType', ServingNodeType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('servingNodeAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 22))),
    namedtype.OptionalNamedType('servingNodeiPv6Address', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 23))),
    namedtype.OptionalNamedType('mMEName', DiameterIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('mMERealm', DiameterIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25))),
    namedtype.OptionalNamedType('userLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 26)))
)


class TWANUserLocationInfo(univ.Sequence):
    pass


TWANUserLocationInfo.componentType = namedtype.NamedTypes(
    namedtype.NamedType('sSID', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('bSSID', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class SubscriptionIDType(univ.Enumerated):
    pass


SubscriptionIDType.namedValues = namedval.NamedValues(
    ('eND-USER-E164', 0),
    ('eND-USER-IMSI', 1),
    ('eND-USER-SIP-URI', 2),
    ('eND-USER-NAI', 3),
    ('eND-USER-PRIVATE', 4)
)


class SubscriptionID(univ.Set):
    pass


SubscriptionID.componentType = namedtype.NamedTypes(
    namedtype.NamedType('subscriptionIDType', SubscriptionIDType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('subscriptionIDData', char.UTF8String().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class MSTimeZone(univ.OctetString):
    pass


MSTimeZone.subtypeSpec = constraint.ValueSizeConstraint(2, 2)


class PGWRecord(univ.Set):
    pass


PGWRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.NamedType('p-GWAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 4))),
    namedtype.NamedType('chargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.NamedType('servingNodeAddress', univ.SequenceOf(componentType=GSNAddress()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('pdpPDNType', PDPType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('servedPDPPDNAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 9))),
    namedtype.OptionalNamedType('dynamicAddressFlag', DynamicAddressFlag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.NamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 16))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.OptionalNamedType('apnSelectionMode', APNSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('iMSsignalingContext', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25))),
    namedtype.OptionalNamedType('externalChargingID', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 26))),
    namedtype.OptionalNamedType('servinggNodePLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 27))),
    namedtype.OptionalNamedType('pSFurnishChargingInformation', PSFurnishChargingInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 28))),
    namedtype.OptionalNamedType('servedIMEISV', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 29))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 30))),
    namedtype.OptionalNamedType('mSTimeZone', MSTimeZone().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 31))),
    namedtype.OptionalNamedType('userLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 32))),
    namedtype.OptionalNamedType('cAMELChargingInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 33))),
    namedtype.OptionalNamedType('listOfServiceData', univ.SequenceOf(componentType=ChangeOfServiceCondition()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 34))),
    namedtype.NamedType('servingNodeType', univ.SequenceOf(componentType=ServingNodeType()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 35))),
    namedtype.OptionalNamedType('servedMNNAI', SubscriptionID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 36))),
    namedtype.OptionalNamedType('p-GWPLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 37))),
    namedtype.OptionalNamedType('startTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 38))),
    namedtype.OptionalNamedType('stopTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 39))),
    namedtype.OptionalNamedType('served3gpp2MEID', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 40))),
    namedtype.OptionalNamedType('pDNConnectionChargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 41))),
    namedtype.OptionalNamedType('iMSIunauthenticatedFlag', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 42))),
    namedtype.OptionalNamedType('userCSGInformation', UserCSGInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 43))),
    namedtype.OptionalNamedType('threeGPP2UserLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 44))),
    namedtype.OptionalNamedType('servedPDPPDNAddressExt', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 45))),
    namedtype.OptionalNamedType('lowPriorityIndicator', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 46))),
    namedtype.OptionalNamedType('dynamicAddressFlagExt', DynamicAddressFlag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 47))),
    namedtype.OptionalNamedType('servingNodeiPv6Address', univ.SequenceOf(componentType=GSNAddress()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 49))),
    namedtype.OptionalNamedType('p-GWiPv6AddressUsed', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 50))),
    namedtype.OptionalNamedType('tWANUserLocationInformation', TWANUserLocationInfo().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 51)))
)


class SGWChange(univ.Boolean):
    pass


class SGWRecord(univ.Set):
    pass


SGWRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.NamedType('s-GWAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 4))),
    namedtype.NamedType('chargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.NamedType('servingNodeAddress', univ.SequenceOf(componentType=GSNAddress()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('pdpPDNType', PDPType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('servedPDPPDNAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 9))),
    namedtype.OptionalNamedType('dynamicAddressFlag', DynamicAddressFlag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('listOfTrafficVolumes', univ.SequenceOf(componentType=ChangeOfCharCondition()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.NamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 16))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.OptionalNamedType('apnSelectionMode', APNSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('iMSsignalingContext', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25))),
    namedtype.OptionalNamedType('servingNodePLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 27))),
    namedtype.OptionalNamedType('servedIMEISV', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 29))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 30))),
    namedtype.OptionalNamedType('mSTimeZone', MSTimeZone().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 31))),
    namedtype.OptionalNamedType('userLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 32))),
    namedtype.OptionalNamedType('sGWChange', SGWChange().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 34))),
    namedtype.NamedType('servingNodeType', univ.SequenceOf(componentType=ServingNodeType()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 35))),
    namedtype.OptionalNamedType('p-GWAddressUsed', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 36))),
    namedtype.OptionalNamedType('p-GWPLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 37))),
    namedtype.OptionalNamedType('startTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 38))),
    namedtype.OptionalNamedType('stopTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 39))),
    namedtype.OptionalNamedType('pDNConnectionChargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 40))),
    namedtype.OptionalNamedType('iMSIunauthenticatedFlag', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 41))),
    namedtype.OptionalNamedType('userCSGInformation', UserCSGInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 42))),
    namedtype.OptionalNamedType('servedPDPPDNAddressExt', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 43))),
    namedtype.OptionalNamedType('lowPriorityIndicator', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 44))),
    namedtype.OptionalNamedType('dynamicAddressFlagExt', DynamicAddressFlag().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 47))),
    namedtype.OptionalNamedType('s-GWiPv6Address', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 48))),
    namedtype.OptionalNamedType('servingNodeiPv6Address', univ.SequenceOf(componentType=GSNAddress()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 49))),
    namedtype.OptionalNamedType('p-GWiPv6AddressUsed', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 50)))
)


class SGSNSMTRecord(univ.Set):
    pass


SGSNSMTRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('msNetworkCapability', MSNetworkCapability().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('serviceCentre', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('recordingEntity', RecordingEntity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('locationArea', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('cellIdentifier', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('eventTimeStamp', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.OptionalNamedType('smsResult', SMSResult().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 11))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('cAMELInformationSMS', CAMELInformationSMS().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 18))),
    namedtype.OptionalNamedType('originatingAddress', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.NamedType('servingNodeType', ServingNodeType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.OptionalNamedType('servingNodeAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 21))),
    namedtype.OptionalNamedType('servingNodeiPv6Address', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 22))),
    namedtype.OptionalNamedType('mMEName', DiameterIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('mMERealm', DiameterIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('userLocationInformation', univ.OctetString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25)))
)


class SGSNMMRecord(univ.Set):
    pass


SGSNMMRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('sgsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 3))),
    namedtype.OptionalNamedType('msNetworkCapability', MSNetworkCapability().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('locationAreaCode', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.OptionalNamedType('cellIdentifier', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('changeLocation', univ.SequenceOf(componentType=ChangeLocation()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.OptionalNamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.OptionalNamedType('sgsnChange', SGSNChange().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 13))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('cAMELInformationMM', CAMELInformationMM().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 20))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.OptionalNamedType('cellPLMNId', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23)))
)


class GPRSRecord(univ.Choice):
    pass


GPRSRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('sgsnPDPRecord', SGSNPDPRecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 20))),
    namedtype.NamedType('sgsnMMRecord', SGSNMMRecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 22))),
    namedtype.NamedType('sgsnSMORecord', SGSNSMORecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 23))),
    namedtype.NamedType('sgsnSMTRecord', SGSNSMTRecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 24))),
    namedtype.NamedType('sGWRecord', SGWRecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 78))),
    namedtype.NamedType('pGWRecord', PGWRecord().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 79)))
)


class GWMBMSRecord(univ.Set):
    pass


GWMBMSRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('mbmsGWAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1))),
    namedtype.NamedType('chargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('listofDownstreamNodes', univ.SequenceOf(componentType=GSNAddress()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('pdpPDNType', PDPType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('servedPDPPDNAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 6))),
    namedtype.OptionalNamedType('listOfTrafficVolumes', univ.SequenceOf(componentType=ChangeOfMBMSCondition()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.NamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 11))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('mbmsInformation', MBMSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 16))),
    namedtype.OptionalNamedType('commonTeid', CTEID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('iPMulticastSourceAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 18)))
)


class LMSI(univ.OctetString):
    pass


LMSI.subtypeSpec = constraint.ValueSizeConstraint(4, 4)


class IMSI_WithLMSI(univ.Sequence):
    pass


IMSI_WithLMSI.componentType = namedtype.NamedTypes(
    namedtype.NamedType('imsi', IMSI()),
    namedtype.NamedType('lmsi', LMSI())
)


class Identity(univ.Choice):
    pass


Identity.componentType = namedtype.NamedTypes(
    namedtype.NamedType('imsi', IMSI()),
    namedtype.NamedType('imsi-WithLMSI', IMSI_WithLMSI())
)


class LCS_Priority(univ.OctetString):
    pass


LCS_Priority.subtypeSpec = constraint.ValueSizeConstraint(1, 1)


class LCSCause(univ.OctetString):
    pass


LCSCause.subtypeSpec = constraint.ValueSizeConstraint(1, 1)


class LCSClientExternalID(univ.Sequence):
    pass


LCSClientExternalID.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('externalAddress', ISDN_AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('extensionContainer', ExtensionContainer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1)))
)


class LCSClientInternalID(univ.Enumerated):
    pass


LCSClientInternalID.namedValues = namedval.NamedValues(
    ('broadcastService', 0),
    ('o-andM-HPLMN', 1),
    ('o-andM-VPLMN', 2),
    ('anonymousLocation', 3),
    ('targetMSsubscribedService', 4)
)


class LCSClientIdentity(univ.Sequence):
    pass


LCSClientIdentity.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('lcsClientExternalID', LCSClientExternalID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0))),
    namedtype.OptionalNamedType('lcsClientDialedByMS', AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('lcsClientInternalID', LCSClientInternalID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


class LCSClientType(univ.Enumerated):
    pass


LCSClientType.namedValues = namedval.NamedValues(
    ('emergencyServices', 0),
    ('valueAddedServices', 1),
    ('plmnOperatorServices', 2),
    ('lawfulInterceptServices', 3)
)


class LCSQoSInfo(univ.OctetString):
    pass


LCSQoSInfo.subtypeSpec = constraint.ValueSizeConstraint(4, 4)


class MCC_MNC(univ.OctetString):
    pass


MCC_MNC.subtypeSpec = constraint.ValueSizeConstraint(3, 3)


class LocationAreaAndCell(univ.Sequence):
    pass


LocationAreaAndCell.componentType = namedtype.NamedTypes(
    namedtype.NamedType('locationAreaCode', LocationAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('cellId', CellId().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('mCC-MNC', MCC_MNC().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2)))
)


class LocationEstimateType(univ.Enumerated):
    pass


LocationEstimateType.namedValues = namedval.NamedValues(
    ('currentLocation', 0),
    ('currentOrLastKnownLocation', 1),
    ('initialLocation', 2),
    ('activateDeferredLocation', 3),
    ('cancelDeferredLocation', 4),
    ('notificationVerificationOnly', 5)
)


class LocationMethod(univ.Enumerated):
    pass


LocationMethod.namedValues = namedval.NamedValues(
    ('msBasedEOTD', 0),
    ('msAssistedEOTD', 1),
    ('assistedGPS', 2),
    ('msBasedOTDOA', 3),
    ('assistedGANSS', 4),
    ('assistedGPSandGANSS', 5)
)


class LocationType(univ.Sequence):
    pass


LocationType.componentType = namedtype.NamedTypes(
    namedtype.NamedType('locationEstimateType', LocationEstimateType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.OptionalNamedType('deferredLocationEventType', DeferredLocationEventType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class MscNo(ISDN_AddressString):
    pass


class NodeAddress(univ.Choice):
    pass


NodeAddress.componentType = namedtype.NamedTypes(
    namedtype.NamedType('iPAddress', IPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 0))),
    namedtype.NamedType('domainName', char.GraphicString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class NotificationToMSUser(univ.Enumerated):
    pass


NotificationToMSUser.namedValues = namedval.NamedValues(
    ('notifyLocationAllowed', 0),
    ('notifyAndVerify-LocationAllowedIfNoResponse', 1),
    ('notifyAndVerify-LocationNotAllowedIfNoResponse', 2),
    ('locationNotAllowed', 3)
)


class PositioningData(univ.OctetString):
    pass


PositioningData.subtypeSpec = constraint.ValueSizeConstraint(1, 33)


class RAIdentity(univ.OctetString):
    pass


RAIdentity.subtypeSpec = constraint.ValueSizeConstraint(6, 6)


class SGSNMBMSRecord(univ.Set):
    pass


SGSNMBMSRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('ggsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 1))),
    namedtype.NamedType('chargingID', ChargingID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('listofRAs', univ.SequenceOf(componentType=RAIdentity()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 3))),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('servedPDPAddress', PDPAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 5))),
    namedtype.OptionalNamedType('listOfTrafficVolumes', univ.SequenceOf(componentType=ChangeOfMBMSCondition()).subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 6))),
    namedtype.NamedType('recordOpeningTime', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.NamedType('duration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 10))),
    namedtype.OptionalNamedType('recordSequenceNumber', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('sgsnPLMNIdentifier', PLMN_Id().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('numberofReceivingUE', univ.Integer().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('mbmsInformation', MBMSInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 17)))
)


class SGSNMOLCSRecord(univ.Set):
    pass


SGSNMOLCSRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('recordingEntity', RecordingEntity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('lcsClientType', LCSClientType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('lcsClientIdentity', LCSClientIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 3))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('sgsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 6))),
    namedtype.NamedType('locationMethod', LocationMethod().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('lcsQos', LCSQoSInfo().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('lcsPriority', LCS_Priority().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.OptionalNamedType('mlcNumber', ISDN_AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.NamedType('eventTimeStamp', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('measurementDuration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('location', LocationAreaAndCell().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 13))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('locationEstimate', Ext_GeographicalInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('positioningData', PositioningData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('lcsCause', LCSCause().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 18))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25)))
)


class SGSNMTLCSRecord(univ.Set):
    pass


SGSNMTLCSRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('recordingEntity', RecordingEntity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.NamedType('lcsClientType', LCSClientType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.NamedType('lcsClientIdentity', LCSClientIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 3))),
    namedtype.NamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('sgsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 6))),
    namedtype.NamedType('locationType', LocationType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 7))),
    namedtype.OptionalNamedType('lcsQos', LCSQoSInfo().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('lcsPriority', LCS_Priority().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.NamedType('mlcNumber', ISDN_AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.NamedType('eventTimeStamp', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('measurementDuration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('notificationToMSUser', NotificationToMSUser().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 13))),
    namedtype.OptionalNamedType('privacyOverride', univ.Null().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('location', LocationAreaAndCell().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 15))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('locationEstimate', Ext_GeographicalInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('positioningData', PositioningData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 18))),
    namedtype.OptionalNamedType('lcsCause', LCSCause().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 20))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 26))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 27)))
)


class SGSNNILCSRecord(univ.Set):
    pass


SGSNNILCSRecord.componentType = namedtype.NamedTypes(
    namedtype.NamedType('recordType', RecordType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('recordingEntity', RecordingEntity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1))),
    namedtype.OptionalNamedType('lcsClientType', LCSClientType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 2))),
    namedtype.OptionalNamedType('lcsClientIdentity', LCSClientIdentity().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 3))),
    namedtype.OptionalNamedType('servedIMSI', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 4))),
    namedtype.OptionalNamedType('servedMSISDN', MSISDN().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 5))),
    namedtype.OptionalNamedType('sgsnAddress', GSNAddress().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 6))),
    namedtype.OptionalNamedType('servedIMEI', IMEI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 7))),
    namedtype.OptionalNamedType('lcsQos', LCSQoSInfo().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 8))),
    namedtype.OptionalNamedType('lcsPriority', LCS_Priority().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 9))),
    namedtype.OptionalNamedType('mlcNumber', ISDN_AddressString().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 10))),
    namedtype.NamedType('eventTimeStamp', TimeStamp().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 11))),
    namedtype.OptionalNamedType('measurementDuration', CallDuration().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 12))),
    namedtype.OptionalNamedType('location', LocationAreaAndCell().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 13))),
    namedtype.OptionalNamedType('routingArea', RoutingAreaCode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 14))),
    namedtype.OptionalNamedType('locationEstimate', Ext_GeographicalInformation().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 15))),
    namedtype.OptionalNamedType('positioningData', PositioningData().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 16))),
    namedtype.OptionalNamedType('lcsCause', LCSCause().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 17))),
    namedtype.OptionalNamedType('diagnostics', Diagnostics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatConstructed, 18))),
    namedtype.OptionalNamedType('nodeID', NodeID().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 19))),
    namedtype.OptionalNamedType('localSequenceNumber', LocalSequenceNumber().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 20))),
    namedtype.NamedType('chargingCharacteristics', ChargingCharacteristics().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 21))),
    namedtype.OptionalNamedType('chChSelectionMode', ChChSelectionMode().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 22))),
    namedtype.OptionalNamedType('rATType', RATType().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 23))),
    namedtype.OptionalNamedType('recordExtensions', ManagementExtensions().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 24))),
    namedtype.NamedType('causeForRecClosing', CauseForRecClosing().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 25)))
)


class ServiceContextID(char.UTF8String):
    pass


class TMSI(univ.OctetString):
    pass


TMSI.subtypeSpec = constraint.ValueSizeConstraint(1, 4)


class SubscriberId(univ.Choice):
    pass


SubscriberId.componentType = namedtype.NamedTypes(
    namedtype.NamedType('imsi', IMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 0))),
    namedtype.NamedType('tmsi', TMSI().subtype(implicitTag=tag.Tag(tag.tagClassContext, tag.tagFormatSimple, 1)))
)


class SystemType(univ.Enumerated):
    pass


SystemType.namedValues = namedval.NamedValues(
    ('unknown', 0),
    ('iuUTRAN', 1),
    ('gERAN', 2)
)


